apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-helloworld
spec:
  containers:
  - name: flask
    image: digitalocean/flask-helloworld:latest
    ports:
    - containerPort: 5000
